### ISSUE TITLE
OIDC testing server unable to start

### ISSUE THREAD

**Issue by bradleybeddoes** [bradleybeddoes/oidc-certification-docker#1]
```
bash-4.3# cd /opt/oidc/oidctest_server_instance/oidc_op
bash-4.3# ./run.sh
Traceback (most recent call last):
  File "config_server.py", line 8, in <module>
    from oic.federation.file_system import FileSystem
ImportError: No module named 'oic.federation'
```

This was working correctly but has been broken since https://github.com/rohe/oidctest/commit/1e718b2b6b7f590e48769d2f52c99b042d5c345b was committed.

Need to determine what dependency we're now missing or if there is a commit to a project that needs to be pushed.

**Comment by bradleybeddoes** [comment]
@rohe I poked around for a good hour on this issue but I can't figure out where it had gone wrong. Any thoughts on fixing this?

**Comment by rohe** [comment]
Ah, you're the victim of a refactoring.
All the stuff dealing with OIDC federations has been moved out of the core OIDC/OAuth2.
It can now be found at https://github.com/openidc/fedoidc .

This means that if you have code based on the old situation when federation stuff was inside oic then
you will have references to 'oic.federation' . With the new regime all of those references should be replaced with 'fedoidc' once you have downloaded/cloned the above mentioned repro and installed it.

**Comment by bradleybeddoes** [comment]
Puzzling, that project and its siblings is already pulled down by the build process https://github.com/bradleybeddoes/oidc-certification-docker/blob/master/Dockerfile#L22 so it always has the latest master and then the setup/install is run for all those projects later in the process https://github.com/bradleybeddoes/oidc-certification-docker/blob/master/Dockerfile#L30

I'll poke around again on Monday, perhaps there is a level of caching somewhere I didn't consider though if that was the case I wouldn't have expected to see the change from oidctest come through either.

**Comment by rohe** [comment]
You had a faulty reference in config_server.py .
I've tried to make sure all the references to oic.federation was remove but I may have missed one.

**Comment by rohe** [comment]
OK, I had cleaned up the oic tree but not the oidctest :-(
Have done that now.

**Comment by bradleybeddoes** [comment]
That seems to have done the trick, the image is operating again and I can access the admin tooling.
